### ISSUE TITLE
Error 500 when click «save» button in Settings > Analytics

### ISSUE THREAD

**Issue by mad99** [neos/neos-googleanalytics#27] opened 2017-07-06 07:27 UTC
Steps to Error : Every click on «save»-button in Backend > Settings > Analytics throws the Error

System:
Neos: 3.1.2
GA: neos/googleanalytics: 2.0.2 + google/apiclient 1.1.8

After save-button-click there is a Error throwing:
Warning: htmlspecialchars() expects parameter 1 to be string, array given in /var/www/path/to/data/src_cur/Data/Temporary/Development/Cache/Code/Fluid_TemplateCache/Configuration_action_index_99a3c9177e6329e413d34a8a9f6959ff72339080.php line 398

After this error, uri: «/neos/administration/googleAnalytics» won't be rendered. Afterwards always the same error. Have to do a «./flow flow:cache:flush --force». Than Settings-Page for GoogleAnalytics is back. But next «save»-click same procedure as every «save»-click...
 
The Tool as it own seam still to work.

**Comment by rolandschuetz** [comment] 2018-09-06 10:18
In the current version, I can't reproduce this error. Is this still valid for you?

**Comment by Sebobo** [comment] 2019-02-01 17:57
I'll close this for now. If it's still an issue please reopen the issue or create a new one.

**Closed by Sebobo** 2019-02-01 17:57 UTC
