### ISSUE TITLE
Migration fails if installed later

### ISSUE THREAD

**Issue by kitsunet** [neos/neos-googleanalytics#28] opened 2017-08-04 13:09 UTC
This also needs the separate package doctrine migration treatment to work out if tables are already named neos_neos or still typo3_neos

**Comment by rolandschuetz** [comment] 2017-08-04 13:45
This is a duplicate of https://github.com/neos/neos-googleanalytics/issues/22

**Closed** 2018-02-01 15:47 UTC
Labels: bug
